#pool: Default
pool: WindowsPool

stages:
- stage: appRepoPublish
  jobs:
  - job: PublishApp
    steps:
    - script: |
       echo "Build.SourcesDirectory: $(Build.SourcesDirectory)"
       dir $(Build.SourcesDirectory)
      displayName: 'Debug file path'
    - task: PowerShell@2
      name: Publish       # <--- Task name, required for output reference
      inputs:
        targetType: 'filePath'
        filePath: '$(Build.SourcesDirectory)/printVersion.ps1'

- stage: createCR
  jobs:
    - job: CreateCRJob
      steps:
        - task: PowerShell@2
          inputs:
            targetType: filePath
            filePath: '$(Build.SourcesDirectory)/CreateCR.ps1'
            arguments: |
              -SNowInstance "dev228661" -destUName "admin" -destPwd "3Bnlvk*2WI^O" -sourceDir "$(Build.SourcesDirectory)"

- stage: appRepoInstall
  dependsOn: appRepoPublish
  variables:
    versionFromPublish: $[ dependencies.appRepoPublish.outputs['PublishApp.Publish.version'] ]
  jobs:
  - job: InstallApp
    steps:
    - script: |
        echo "Installing version: $(versionFromPublish)"
      displayName: 'Print version from publish stage'
#    - task: PowerShell@2
#      inputs:
#        targetType: 'filePath'
#        filePath: '$(Build.SourcesDirectory)/installVersion.ps1'
#        arguments: '-version $(versionFromPublish)'