trigger:
- main

#pool: Default
pool: WindowsPool

stages:
  - stage: PrintVersion
    displayName: 'Print Version'
    jobs:
      - job: PrintVersionJob
        displayName: 'Run printVersion.ps1'
        steps:
          - task: PowerShell@2
            name: PrintVersionTask
            displayName: 'Run printVersion.ps1'
            inputs:
              targetType: 'filePath'
              filePath: './printVersion.ps1'

  - stage: InstallVersion
    displayName: 'Install Version'
    dependsOn: PrintVersion  # This stage will run after PrintVersion
    jobs:
      - job: InstallVersionJob
        displayName: 'Run installVersion.ps1'
        variables:
          versionFromPrint: $[ dependencies.PrintVersion.outputs['getVersion.version'] ]
        steps:
          - script: |
             echo "Version passed from previous: $(versionFromPrint)"
            displayName: 'Debug Version Output'
          - task: PowerShell@2
            displayName: 'Run installVersion.ps1'
            inputs:
              targetType: 'filePath'
              filePath: './installVersion.ps1'
              arguments: '-version $(versionFromPrint)'  # Pass the version as an argument