#pool: Default
pool: WindowsPool

stages:
- stage: appRepoPublish
  jobs:
  - job: PublishApp
    steps:
    - script: |
       echo "Build.SourcesDirectory: $(Build.SourcesDirectory)"
       dir $(Build.SourcesDirectory)
      displayName: 'Debug file path'
    - task: PowerShell@2
      name: Publish       # <--- Task name, required for output reference
      inputs:
        targetType: 'filePath'
        filePath: '$(Build.SourcesDirectory)/printVersion.ps1'

- stage: appRepoInstall
  dependsOn: appRepoPublish
  variables:
    versionFromPublish: $[ dependencies.appRepoPublish.outputs['PublishApp.Publish.version'] ]
  jobs:
  - job: InstallApp
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'filePath'
        filePath: '$(Build.SourcesDirectory)/installVersion.ps1'
        arguments: '-version $(versionFromPublish)'